version: '3.9'

services:
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: yusufdrymz
      MYSQL_USER: 030121008
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - wordpress:/var/www/html

  certbot:
    image: certbot/certbot
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --yusuf.erkamyed@gmail.com--agree-tos --no-eff-email -d yusufdrymz.live

volumes:
  wordpress:
